# This file is generated by experiments/Deciding_EA_equivalence_via_invariants/generate_luts.jl.
# Do not edit it by hand; edit experiments/Deciding_EA_equivalence_via_invariants/table1_data.jl instead.

const KALEYSKI_TABLE1_GENERATED_LUTS = Dict{Tuple{Int, String}, Vector{Int}}(
