export is_apn

export gamma_rank,
       delta_rank

export matrix_to_sbox,
       permutation_cycle_structure,
       matrix_cycle_structure,
       same_cycle_structure,
       int_to_field_element,
       interpolate_sbox_polynomial,
       format_sbox_polynomial

export generate_tuples_file,
       generate_tuple_constants_file,
       generate_tuple_constants_files,
       generate_tuple_matrix_constants_file,
       generate_tuple_matrix_constants_files,
       extract_matrices_from_tuple_lut,
       load_precomputed_tuple_constants,
       load_precomputed_tuple_matrix_constants,
       all_precomputed_tuple_class_indices,
       parse_class_indices_argument,
       normalize_precomputed_tuple_classes,
       precomputed_tuple_matrices,
       precomputed_tuple_row,
       precomputed_tuple_sboxes,
       save_search_result_constant,
       search_result_constant_name,
       tuple_to_sbox_row,
       tuples_to_sbox_rows

export APNCoefficient,
       OneCoefficient,
       PowerCoefficient,
       APNTerm,
       APNTraceTerm,
       APNFunction,
       APNFamilyMatch,
       APNComponent,
       APNMonomial,
       APNTraceMonomial,
       APNAbsoluteTrace,
       APNRelativeTrace,
       APNReference,
       APNDefinition,
       x,
       pterm,
       Tr,
       trace_term,
       xpow,
       reference,
       absolute_trace,
       relative_trace,
       classify_family,
       belongs_to_family,
       family_c3,
       family_c4,
       family_c5,
       family_c6